/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => NoteSplitterPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/obsidian/note-splitter-settings-tab.ts
var import_obsidian = require("obsidian");
var NoteSplitterSettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Output folder").setDesc(
      "The folder to save split notes in. If empty, the folder of the original note will be used."
    ).addText(
      (text) => text.setValue(this.plugin.settings.saveFolderPath).onChange(async (value) => {
        this.plugin.settings.saveFolderPath = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Delimiter").setDesc("The sequence of characters to split by.").addText(
      (text) => text.setValue(this.plugin.settings.delimiter).onChange(async (value) => {
        this.plugin.settings.delimiter = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Remove delimiter").setDesc(
      "If enabled, the delimiter will not be included in the content of split notes."
    ).addToggle(
      (cb) => cb.setValue(this.plugin.settings.removeDelimiter).onChange(async (value) => {
        this.plugin.settings.removeDelimiter = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Use first line as title").setDesc(
      "If enabled, the first line of split content will be used as the title of the split note. If disabled, a timestamp will be used. e.g. note-splitter-1702591910"
    ).addToggle(
      (text) => text.setValue(this.plugin.settings.useContentAsTitle).onChange(async (value) => {
        this.plugin.settings.useContentAsTitle = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Append to split content").setDesc("Text to append to the split content.").addText(
      (text) => text.setValue(this.plugin.settings.appendToSplitContent).onChange(async (value) => {
        this.plugin.settings.appendToSplitContent = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Delete original").setDesc("Delete the original note after a successful split.").addToggle(
      (text) => text.setValue(this.plugin.settings.deleteOriginalNote).onChange(async (value) => {
        this.plugin.settings.deleteOriginalNote = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/splitter/split-by-delimiter.ts
var import_obsidian2 = require("obsidian");

// src/splitter/remove-frontmatter-block.ts
var removeFrontmatterBlock = (content) => {
  const FRONTMATTER_REGEX = /^---[\s\S]*?---/;
  return content.replace(FRONTMATTER_REGEX, "").trim();
};

// src/splitter/sanitize-file-name.ts
var sanitizeFileName = (name, isWindows) => {
  if (isWindows) {
    name = name.replace(/\?/g, "");
    name = name.replace(/</g, "");
    name = name.replace(/>/g, "");
    name = name.replace(/"/g, "");
    name = name.replace(/\*/g, "");
    name = name.replace(/`/g, "");
  }
  name = name.replace(/:/g, "");
  name = name.replace(/\|/g, "");
  name = name.replace(/\\/g, "");
  name = name.replace(/\//g, "");
  name = name.replace(/\[/g, "");
  name = name.replace(/\]/g, "");
  name = name.replace(/#/g, "");
  name = name.replace(/\^/g, "");
  return name.trim();
};

// src/splitter/truncate-file-name.ts
var truncateFileName = (name, extension) => {
  const MAX_LENGTH = 255;
  let length = name.length;
  if (length > MAX_LENGTH) {
    length = MAX_LENGTH;
  }
  return name.substring(0, length - extension.length) + extension;
};

// src/splitter/split-by-delimiter.ts
var splitByDelimiter = async (fileSystem, notify, file, isWindows, settings) => {
  const {
    delimiter,
    saveFolderPath,
    useContentAsTitle,
    appendToSplitContent,
    removeDelimiter,
    deleteOriginalNote
  } = settings;
  const escapedDelimiter = delimiter.replace(/\\n/g, "\n");
  if (escapedDelimiter === "") {
    notify("No delimiter set. Please set a delimiter in the settings.");
    return;
  }
  const content = await fileSystem.read(file);
  const contentWithoutFrontmatter = removeFrontmatterBlock(content);
  if (contentWithoutFrontmatter === "") {
    notify("No content to split.");
    return;
  }
  const splitContent = contentWithoutFrontmatter.split(escapedDelimiter).map((splitContent2) => splitContent2.trim()).filter((splitContent2) => splitContent2 !== "").map((splitContent2) => {
    if (!removeDelimiter) {
      return splitContent2 + delimiter;
    }
    return splitContent2;
  });
  if (splitContent.length === 1) {
    notify("Only one section of content found. Nothing to split.");
    return;
  }
  const folderPath = saveFolderPath || "";
  try {
    await fileSystem.createFolder(folderPath);
  } catch (err) {
  }
  let filesCreated = 0;
  for (const [i, originalContent] of splitContent.entries()) {
    let updatedContent = originalContent;
    if (appendToSplitContent.length > 0) {
      updatedContent += appendToSplitContent;
    }
    let fileName = "";
    if (useContentAsTitle) {
      fileName = originalContent.split("\n")[0] + ".md";
    } else {
      fileName = `split-note-${Date.now() + i}.md`;
    }
    fileName = sanitizeFileName(fileName, isWindows);
    fileName = truncateFileName(fileName, ".md");
    const filePath = (0, import_obsidian2.normalizePath)(`${folderPath}/${fileName}`);
    try {
      await fileSystem.create(filePath, updatedContent);
      filesCreated++;
    } catch (err) {
      if (err.message.includes("already exists")) {
        const newFilePath = `${folderPath}/Split conflict ${crypto.randomUUID()}.md`;
        try {
          await fileSystem.create(newFilePath, updatedContent);
          filesCreated++;
        } catch (err2) {
          console.error(err2);
          notify(`Error creating file: ${err2.message}`);
        }
        continue;
      }
      notify(`Error creating file: ${err.message}`);
      console.log(err);
    }
  }
  if (deleteOriginalNote && filesCreated === splitContent.length) {
    await fileSystem.delete(file);
  }
  notify("Split into " + filesCreated + " note" + (filesCreated > 1 ? "s" : "") + ".");
};

// src/main.ts
var DEFAULT_SETTINGS = {
  saveFolderPath: "note-splitter",
  useContentAsTitle: false,
  delimiter: "\\n",
  removeDelimiter: true,
  appendToSplitContent: "",
  deleteOriginalNote: false
};
var NoteSplitterPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new NoteSplitterSettingsTab(this.app, this));
    this.addCommand({
      id: "split-by-delimiter",
      name: "Split by delimiter",
      callback: async () => {
        const view = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
        if (view === null) {
          new import_obsidian3.Notice("Please open a markdown note.");
          return;
        }
        const file = view.file;
        if (file === null) {
          new import_obsidian3.Notice("No file found for this note.");
          return;
        }
        if (view.getMode() !== "source") {
          new import_obsidian3.Notice("Please switch to editing mode to split this note.");
          return;
        }
        const fileSystem = {
          create: (filePath, content) => this.app.vault.create(filePath, content),
          createFolder: (folderPath) => this.app.vault.createFolder(folderPath),
          delete: (file2) => this.app.vault.delete(file2),
          read: (file2) => this.app.vault.read(file2)
        };
        const notifier = (message) => new import_obsidian3.Notice(message);
        await splitByDelimiter(fileSystem, notifier, file, import_obsidian3.Platform.isWin, this.settings);
      }
    });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};

/* nosourcemap */