collections:
  days:
    output: true
    permalink: :name
  crews:
    output: true
    permalink: :name
  tags:
    output: true
    permalink: /tags/:name/
  years:
    output: true
    permalink: /years/:name/

defaults:
  - scope:
      path: ""
      type: "crews"
    values:
      layout: "crew"
  - scope:
      path: ""
      type: "days"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag